import { Poppins } from "next/font/google";
import "./globals.css";
import "./imdos.css";
import { ImdosProvider } from "@/providers/ImdosProvider";

const poppins = Poppins({
  weight: ["300", "600"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ImdosProvider>{children}</ImdosProvider>
      </body>
    </html>
  );
}
